project_name: vf-admin
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
    - -trimpath
    ldflags:
    - -s -w -X main.version={{ .Version }} -X main.tag={{ .Tag }} -X main.date={{ .CommitDate }}
archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^ci'
      - '^Merge'
      - Merge pull request
      - Merge branch
release:
  prerelease: auto
