name: Go Test
on: [push, pull_request]
jobs:
  test:
    # Run tests on multiple operating systems using Go v1.16
    strategy:
      matrix:
        go-version: [1.16]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    # Install Go
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    # Checkout the commit SHA that triggered the workflow
    - name: Checkout code
      uses: actions/checkout@v2
    # Run tests
    - name: Test
      run: go test ./...
